import RailCore

enum JourneyCompletionStrings {
    static let table: [String: [Localization.Language: String]] = [
        "ios.ai.subscription": [.zhHant: "ChatGPT 訂閱", .zhHans: "ChatGPT 订阅", .ja: "ChatGPTサブスクリプション", .en: "ChatGPT subscription"],
        "ios.ai.subscriptionInfo": [.zhHant: "使用 Codex 訂閱介面，登入頁會顯示 Codex。這是實驗性整合，模型與額度由帳號決定。點擊補全會將旅程資料與辨識文字傳送至 OpenAI。", .zhHans: "使用 Codex 订阅接口，登录页会显示 Codex。这是实验性集成，模型与额度由账号决定。点击补全会将旅程资料与识别文字发送至 OpenAI。", .ja: "Codexのサブスクリプション接続を使用するため、認証画面にはCodexと表示されます。実験的な連携で、モデルと利用枠はアカウントに依存します。補完すると旅程情報と認識テキストがOpenAIに送信されます。", .en: "Uses the Codex subscription interface, so authorization displays Codex. This integration is experimental; models and limits depend on your account. Completing sends journey details and recognized text to OpenAI."],
        "ios.ai.account": [.zhHant: "帳號", .zhHans: "账号", .ja: "アカウント", .en: "Account"],
        "ios.ai.plan": [.zhHant: "方案", .zhHans: "套餐", .ja: "プラン", .en: "Plan"],
        "ios.ai.model": [.zhHant: "模型", .zhHans: "模型", .ja: "モデル", .en: "Model"],
        "ios.ai.refreshModels": [.zhHant: "重新載入模型", .zhHans: "重新加载模型", .ja: "モデルを再読み込み", .en: "Reload models"],
        "ios.ai.complete": [.zhHant: "使用訂閱模型補全", .zhHans: "使用订阅模型补全", .ja: "サブスクリプションで補完", .en: "Complete with subscription"],
        "ios.ai.signIn": [.zhHant: "登入 ChatGPT 訂閱", .zhHans: "登录 ChatGPT 订阅", .ja: "ChatGPTサブスクリプションにログイン", .en: "Sign in with ChatGPT subscription"],
        "ios.ai.signOut": [.zhHant: "登出此裝置", .zhHans: "退出此设备", .ja: "この端末からログアウト", .en: "Sign out on this device"],
        "ios.ai.deviceInstructions": [.zhHant: "開啟 OpenAI 授權頁，登入自己的帳號並輸入上方代碼，再返回此 App。若帳號要求，請先啟用裝置碼登入。", .zhHans: "打开 OpenAI 授权页，登录自己的账号并输入上方代码，再返回此 App。若账号要求，请先启用设备码登录。", .ja: "OpenAIの認証ページを開き、ご自身のアカウントでログインして上のコードを入力し、このアプリに戻ってください。必要に応じてデバイスコード認証を有効にしてください。", .en: "Open the OpenAI authorization page, sign in to your account, enter this code, then return here. Enable device-code login in your account if prompted."],
        "ios.ai.authorize": [.zhHant: "開啟 OpenAI 授權頁", .zhHans: "打开 OpenAI 授权页", .ja: "OpenAIの認証ページを開く", .en: "Open OpenAI authorization"],
        "ios.ai.waitingLogin": [.zhHant: "等待授權…", .zhHans: "等待授权…", .ja: "認証を待っています…", .en: "Waiting for authorization…"],
        "ios.ai.working": [.zhHant: "正在連線…", .zhHans: "正在连接…", .ja: "処理中…", .en: "Working…"],
        "ios.ai.cancelRequest": [.zhHant: "取消請求", .zhHans: "取消请求", .ja: "リクエストをキャンセル", .en: "Cancel request"],
        "ios.ai.noModels": [.zhHant: "帳號未回傳可用模型。請稍後重新載入。", .zhHans: "账号未返回可用模型。请稍后重新加载。", .ja: "利用可能なモデルが返されませんでした。後で再読み込みしてください。", .en: "No available models were returned. Reload later."],
        "ios.ai.title": [.zhHant: "AI 補全", .zhHans: "AI 补全", .ja: "AIで補完", .en: "AI completion"],
        "ios.ai.instructions": [.zhHant: "分享提示詞，在 ChatGPT 登入後貼上並執行，再將 JSON 回覆貼回下方。只會傳送你選擇分享的文字。", .zhHans: "分享提示词，在 ChatGPT 登录后粘贴并执行，再将 JSON 回复贴回下方。只会发送你选择分享的文字。", .ja: "プロンプトを共有し、ChatGPTにログインして貼り付けて実行します。JSONの回答を下に貼り付けてください。共有したテキストのみが送信されます。", .en: "Share the prompt, sign in to ChatGPT and paste it to run. Paste the JSON reply below. Only text you choose to share is sent."],
        "ios.ai.share": [.zhHant: "分享提示詞", .zhHans: "分享提示词", .ja: "プロンプトを共有", .en: "Share prompt"],
        "ios.ai.open": [.zhHant: "開啟 ChatGPT／登入", .zhHans: "打开 ChatGPT／登录", .ja: "ChatGPTを開く／ログイン", .en: "Open ChatGPT / sign in"],
        "ios.ai.prompt": [.zhHant: "查看提示詞", .zhHans: "查看提示词", .ja: "プロンプトを表示", .en: "View prompt"],
        "ios.ai.response": [.zhHant: "貼上 JSON 回覆", .zhHans: "粘贴 JSON 回复", .ja: "JSONの回答を貼り付け", .en: "Paste JSON reply"],
        "ios.ai.preview": [.zhHant: "預覽補全", .zhHans: "预览补全", .ja: "補完をプレビュー", .en: "Preview completion"],
        "ios.ai.review": [.zhHant: "請核對下列新增資訊與回覆來源。套用只會填入空白欄位，儲存旅程後才會保留。", .zhHans: "请核对下列新增信息与回复来源。应用只会填入空白字段，保存旅程后才会保留。", .ja: "追加情報と回答の出典を確認してください。空欄のみを補完し、旅程の保存後に保持されます。", .en: "Check the additions and response sources. Applying fills empty fields only; save or import the journey to keep them."],
        "ios.ai.sources": [.zhHant: "回覆與來源", .zhHans: "回复与来源", .ja: "回答と出典", .en: "Response and sources"],
        "ios.ai.apply": [.zhHant: "套用至草稿", .zhHans: "应用到草稿", .ja: "下書きに適用", .en: "Apply to draft"],
        "ios.ai.invalid": [.zhHant: "無法套用，請檢查回覆格式。", .zhHans: "无法应用，请检查回复格式。", .ja: "回答の形式を確認してください。", .en: "Could not apply. Check the response format."],
        "ios.ai.eligible": [.zhHant: "請先填入起訖站，以及日期、時間、路線、公司或車號等辨識資訊。", .zhHans: "请先填写起终站，以及日期、时间、线路、公司或车号等识别信息。", .ja: "発着駅と、日付・時刻・路線・会社・列車番号などの情報を入力してください。", .en: "Enter endpoints and identifying details such as date, time, line, operator or train number first."],
        "ios.ai.rawTitle": [.zhHant: "貼上列車資訊", .zhHans: "粘贴列车信息", .ja: "列車情報を貼り付け", .en: "Paste train information"],
        "ios.ai.rawInstructions": [.zhHant: "先在裝置上擷取車站、時間與車次。請確認每個資料庫車站後，才可送出 AI 請求。", .zhHans: "先在设备上提取车站、时间与车次。请确认每个数据库车站后，才可发送 AI 请求。", .ja: "駅・時刻・列車名を端末上で抽出します。データベースの駅を確認してからAIに送信できます。", .en: "Stations, times, and service details are extracted on this device. Confirm each database station before sending an AI request."],
        "ios.ai.rawInput": [.zhHant: "列車資訊", .zhHans: "列车信息", .ja: "列車情報", .en: "Train information"],
        "ios.ai.extract": [.zhHant: "在裝置上擷取", .zhHans: "在设备上提取", .ja: "端末上で抽出", .en: "Extract on device"],
        "ios.ai.loadingCatalog": [.zhHant: "正在載入車站資料庫…", .zhHans: "正在加载车站数据库…", .ja: "駅データベースを読み込み中…", .en: "Loading station database…"],
        "ios.ai.stationMatch": [.zhHant: "資料庫車站", .zhHans: "数据库车站", .ja: "データベースの駅", .en: "Database station"],
        "ios.ai.chooseStation": [.zhHant: "選擇車站", .zhHans: "选择车站", .ja: "駅を選択", .en: "Choose station"],
        "ios.ai.confirmExtracted": [.zhHant: "確認擷取的草稿", .zhHans: "确认提取的草稿", .ja: "抽出した下書きを確認", .en: "Confirm extracted draft"],
        "ios.ai.confirmed": [.zhHant: "已確認擷取的草稿", .zhHans: "已确认提取的草稿", .ja: "抽出した下書きを確認済み", .en: "Extracted draft confirmed"],
        "ios.ai.unmatched": [.zhHant: "未使用的文字", .zhHans: "未使用的文字", .ja: "未使用のテキスト", .en: "Unused text"],
        "ios.ai.notEnoughStops": [.zhHant: "至少需要辨識兩個車站。", .zhHans: "至少需要识别两个车站。", .ja: "少なくとも2駅を認識する必要があります。", .en: "At least two stations must be recognized."],
        "ios.ai.catalogUnavailable": [.zhHant: "無法載入此地區的車站資料庫。", .zhHans: "无法加载此地区的车站数据库。", .ja: "この地域の駅データベースを読み込めません。", .en: "The station database for this region could not be loaded."],
        "ios.ai.date": [.zhHant: "日期", .zhHans: "日期", .ja: "日付", .en: "Date"],
        "ios.ai.origin": [.zhHant: "起點", .zhHans: "起点", .ja: "出発駅", .en: "Origin"],
        "ios.ai.destination": [.zhHant: "終點", .zhHans: "终点", .ja: "到着駅", .en: "Destination"],
        "ios.ai.station": [.zhHant: "車站", .zhHans: "车站", .ja: "駅", .en: "Station"],
        "ios.ai.service": [.zhHant: "車次", .zhHans: "车次", .ja: "列車", .en: "Service"],
        "ios.ai.english": [.zhHant: "英文名稱", .zhHans: "英文名称", .ja: "英語名", .en: "English name"],
        "ios.ai.type": [.zhHant: "列車種別", .zhHans: "列车种别", .ja: "種別", .en: "Train type"],
        "ios.ai.vehicle": [.zhHant: "車型", .zhHans: "车型", .ja: "車両形式", .en: "Vehicle"],
        "ios.ai.company": [.zhHant: "公司", .zhHans: "公司", .ja: "会社", .en: "Operator"],
        "ios.ai.direction": [.zhHant: "方向", .zhHans: "方向", .ja: "方向", .en: "Direction"],
        "ios.ai.lines": [.zhHant: "路線", .zhHans: "线路", .ja: "路線", .en: "Lines"],
        "ios.ai.arrival": [.zhHant: "抵達", .zhHans: "到达", .ja: "到着", .en: "Arrival"],
        "ios.ai.departure": [.zhHant: "出發", .zhHans: "出发", .ja: "出発", .en: "Departure"],
        "ios.ai.platform": [.zhHant: "月台", .zhHans: "站台", .ja: "のりば", .en: "Platform"],
        "ios.ai.unchanged": [.zhHant: "沒有新增資訊", .zhHans: "没有新增信息", .ja: "追加情報なし", .en: "No new information"],
    ]
}
