import RailCore

enum RouteGuideStrings {
    static let table: AppStrings.Table = [
        "ios.routeGuide.pendingMileageNote": [
            .en: "Routes pending confirmation are excluded from precise mileage.",
            .zhHans: "待确认路线不计入精确里程。", .zhHant: "待確認路線不計入精確里程。", .ja: "確認待ちの経路は正確な距離に含めません。",
        ],
        "ios.routeGuide.confirmedDistance": [
            .en: "Confirmed distance", .zhHans: "已确认里程", .zhHant: "已確認里程", .ja: "確認済み距離",
        ],
        "ios.routeGuide.unknownDistance": [
            .en: "Distance unknown", .zhHans: "里程未知", .zhHant: "里程未知", .ja: "距離不明",
        ],
        "ios.routeGuide.via": [
            .en: "Required stations (optional)", .zhHans: "必经站（可选）", .zhHant: "必經站（可選）", .ja: "経由駅（任意）",
        ],
        "ios.routeGuide.addVia": [
            .en: "Add required station", .zhHans: "添加必经站", .zhHant: "新增必經站", .ja: "経由駅を追加",
        ],
        "ios.routeGuide.pending": [
            .en: "Route pending confirmation", .zhHans: "路线待确认", .zhHant: "路線待確認", .ja: "経路の確認待ち",
        ],
        "ios.routeGuide.keepPending": [
            .en: "Keep route pending confirmation", .zhHans: "保留为待确认路线", .zhHant: "保留為待確認路線", .ja: "経路を確認待ちにする",
        ],
        "ios.routeGuide.pendingNote": [
            .en: "Save the journey with its route pending confirmation. No route line or precise mileage will be inferred.",
            .zhHans: "可保存行程，路线保留待确认；不强行连线，也不推算精确里程。",
            .zhHant: "可儲存行程，路線保留待確認；不強行連線，也不推算精確里程。",
            .ja: "経路を確認待ちとして行程を保存できます。経路線や正確な距離は推定しません。",
        ],
        "ios.routeGuide.incompleteSearch": [
            .en: "These are candidate paths, not proof of a unique route. Network coverage is unverified or the search was limited. Select a path you can confirm, or keep it pending.",
            .zhHans: "这些是候选走向，不能证明路线唯一。路网覆盖尚未核实或搜索受限；请选择能够确认的走向，或保留待确认。",
            .zhHant: "這些是候選走向，不能證明路線唯一。路網覆蓋尚未核實或搜尋受限；請選擇能夠確認的走向，或保留待確認。",
            .ja: "候補は経路が唯一である証明ではありません。網羅性が未確認または探索が制限されています。確認できる経路を選ぶか、確認待ちにしてください。",
        ],
        "ios.routeGuide.inferredPass": [
            .en: "Inferred passing station · time unknown", .zhHans: "推测通过站 · 通过、时刻未知",
            .zhHant: "推測通過站 · 通過、時刻未知", .ja: "推定通過駅・時刻不明",
        ],
        "ios.routeGuide.passUnknown": [
            .en: "Passing · time unknown", .zhHans: "通过、时刻未知", .zhHant: "通過、時刻未知", .ja: "通過・時刻不明",
        ],
        "ios.routeGuide.infer": [
            .en: "Automatically infer route sections", .zhHans: "自动推测区间",
            .zhHant: "自動推測區間", .ja: "経路区間を自動推定",
        ],
        "ios.routeGuide.manual": [
            .en: "Choose route sections manually", .zhHans: "手动选择区间",
            .zhHant: "手動選擇區間", .ja: "経路区間を手動で選択",
        ],
        "ios.routeGuide.inferenceNote": [
            .en: "Find candidate paths through your recorded stations. Only a unique route from a complete search can fill automatically. Inferred intermediate stations remain visible as passing, with unknown times.",
            .zhHans: "根据已记录车站查找候选走向；仅在路网与搜索完整且唯一可达时自动填入。推测中间站继续显示为“通过、时刻未知”。",
            .zhHant: "根據已記錄車站尋找候選走向；僅在路網與搜尋完整且唯一可達時自動填入。推測中間站繼續顯示為「通過、時刻未知」。",
            .ja: "記録駅を経由する候補を検索します。網羅的な探索で唯一と確認できる場合のみ自動補完します。推定した中間駅は「通過・時刻不明」と表示します。",
        ],
        "ios.routeGuide.inferenceFailed": [
            .en: "No connected route could be inferred through every recorded station. Select a range manually or check the stations.",
            .zhHans: "无法推测连接全部已记录车站的路线。请手动选择区间或检查车站。",
            .zhHant: "無法推測連接全部已記錄車站的路線。請手動選擇區間或檢查車站。",
            .ja: "記録された全駅を結ぶ経路を推定できません。区間を手動で選ぶか、駅を確認してください。",
        ],
        "ios.routeGuide.title": [
            .en: "Choose the railway route",
            .zhHans: "选择实际铁路走向",
            .zhHant: "選擇實際鐵路走向",
            .ja: "実際の鉄道経路を選択",
        ],
        "ios.routeGuide.help": [
            .en: "Compare the mapped paths, preview an option, then confirm each part of the route.",
            .zhHans: "比较地图上的走向，预览后逐段确认。",
            .zhHant: "比較地圖上的走向，預覽後逐段確認。",
            .ja: "地図上の経路を比較し、プレビューして区間ごとに確定します。",
        ],
        "ios.routeGuide.step": [
            .en: "Route choice {current} of {total}",
            .zhHans: "第 {current} / {total} 处路线选择",
            .zhHant: "第 {current} / {total} 處路線選擇",
            .ja: "経路の選択 {current} / {total}",
        ],
        "ios.routeGuide.option": [
            .en: "Option {number}",
            .zhHans: "方案 {number}",
            .zhHant: "方案 {number}",
            .ja: "候補 {number}",
        ],
        "ios.routeGuide.preview": [
            .en: "Preview",
            .zhHans: "预览",
            .zhHant: "預覽",
            .ja: "プレビュー",
        ],
        "ios.routeGuide.confirm": [
            .en: "Confirm this path",
            .zhHans: "确认这一段",
            .zhHant: "確認這一段",
            .ja: "この区間を確定",
        ],
        "ios.routeGuide.previous": [
            .en: "Previous choice",
            .zhHans: "上一处",
            .zhHant: "上一處",
            .ja: "前の選択へ",
        ],
        "ios.routeGuide.review": [
            .en: "Review the full route",
            .zhHans: "检查完整路线",
            .zhHant: "檢查完整路線",
            .ja: "経路全体を確認",
        ],
        "ios.routeGuide.reviewTitle": [
            .en: "Review your route",
            .zhHans: "检查所选路线",
            .zhHant: "檢查所選路線",
            .ja: "選択した経路を確認",
        ],
        "ios.routeGuide.apply": [
            .en: "Apply route",
            .zhHans: "应用路线",
            .zhHant: "套用路線",
            .ja: "経路を適用",
        ],
        "ios.routeGuide.unsure": [
            .en: "I’m not sure",
            .zhHans: "暂时无法判断",
            .zhHant: "暫時無法判斷",
            .ja: "まだ判断できない",
        ],
        "ios.routeGuide.noCandidate": [
            .en: "None of these paths is correct",
            .zhHans: "这些走向都不正确",
            .zhHant: "這些走向都不正確",
            .ja: "正しい経路がない",
        ],
        "ios.routeGuide.emptyDetail": [
            .en: "No verified railway path is available for these stations. Your ride has not changed.",
            .zhHans: "这些车站之间暂无可核实的铁路走向，行程尚未改变。",
            .zhHant: "這些車站之間暫無可核實的鐵路走向，行程尚未改變。",
            .ja: "この駅間で確認できる鉄道経路がありません。記録は変更されていません。",
        ],
        "ios.routeGuide.fullRoute": [
            .en: "Inspect full route",
            .zhHans: "查看全程",
            .zhHant: "查看全程",
            .ja: "経路全体を表示",
        ],
        "ios.routeGuide.inserted": [
            .en: "Stations to add ({count})",
            .zhHans: "将补入的车站（{count}）",
            .zhHant: "將補入的車站（{count}）",
            .ja: "追加する駅（{count}）",
        ],
        "ios.routeGuide.removed": [
            .en: "Stations to remove ({count})",
            .zhHans: "将移除的车站（{count}）",
            .zhHant: "將移除的車站（{count}）",
            .ja: "削除する駅（{count}）",
        ],
        "ios.routeGuide.protected": [
            .en: "Recorded details need confirmation",
            .zhHans: "删除已有记录需确认",
            .zhHant: "刪除已有記錄需確認",
            .ja: "記録済み情報の削除には確認が必要",
        ],
        "ios.routeGuide.unchanged": [
            .en: "No stations will be added or removed.",
            .zhHans: "车站列表无需增删。",
            .zhHant: "車站列表無需增刪。",
            .ja: "駅の追加・削除はありません。",
        ],
        "ios.routeGuide.changeTitle": [
            .en: "Change an earlier choice?",
            .zhHans: "修改之前的选择？",
            .zhHant: "修改之前的選擇？",
            .ja: "前の選択を変更しますか？",
        ],
        "ios.routeGuide.changeDetail": [
            .en: "This path changes {count} later route choices. Those choices will need to be confirmed again.",
            .zhHans: "此走向会影响后面 {count} 处选择，需要重新确认。",
            .zhHant: "此走向會影響後面 {count} 處選擇，需要重新確認。",
            .ja: "この経路では後の {count} 件の選択が変わるため、再確認が必要です。",
        ],
        "ios.routeGuide.changeConfirm": [
            .en: "Change path",
            .zhHans: "修改走向",
            .zhHant: "修改走向",
            .ja: "経路を変更",
        ],
        "ios.routeGuide.keepSelection": [
            .en: "Keep current choice",
            .zhHans: "保留当前选择",
            .zhHant: "保留目前選擇",
            .ja: "現在の選択を維持",
        ],
        "ios.routeGuide.geometryUnavailable": [
            .en: "Some route geometry is unavailable.",
            .zhHans: "部分线路尚无地图几何数据。",
            .zhHant: "部分路線尚無地圖幾何資料。",
            .ja: "一部の経路の地図データがありません。",
        ],
        "ios.routeGuide.lineOption": [
            .en: "Mapped alignment",
            .zhHans: "地图中的实际走向",
            .zhHant: "地圖中的實際走向",
            .ja: "地図上の経路",
        ],
        "ios.routeGuide.progress": [
            .en: "{confirmed} of {total} route choices confirmed",
            .zhHans: "已确认 {confirmed} / {total} 处",
            .zhHant: "已確認 {confirmed} / {total} 處",
            .ja: "{total} 件中 {confirmed} 件を確定",
        ],
        "ios.routeGuide.routeUnavailable": [
            .en: "This path cannot be applied to the current stops. Choose another path or return to editing.",
            .zhHans: "此走向无法应用于当前车站记录，请选择其他走向或返回编辑。",
            .zhHant: "此走向無法套用於目前車站記錄，請選擇其他走向或返回編輯。",
            .ja: "この経路は現在の駅記録に適用できません。別の経路を選ぶか編集に戻ってください。",
        ],
        "ios.routeGuide.protectedDetail": [
            .en: "Some removed stations contain recorded times, platforms, or stop details. Review the next confirmation before replacing them.",
            .zhHans: "部分待移除车站已有时刻、站台或停站记录，应用前还需确认删除。",
            .zhHant: "部分待移除車站已有時刻、月台或停站記錄，套用前還需確認刪除。",
            .ja: "削除する駅に時刻・番線・停車情報があります。適用前に削除の確認が必要です。",
        ],
        "ios.routeGuide.previewNote": [
            .en: "Preview only. Your ride changes when you apply the full route.",
            .zhHans: "当前仅为预览，应用完整路线后才会修改行程。",
            .zhHant: "目前僅為預覽，套用完整路線後才會修改行程。",
            .ja: "現在はプレビューです。経路全体を適用すると記録が変更されます。",
        ],
        "ios.routeGuide.wholeRoute": [
            .en: "Whole route",
            .zhHans: "完整路线",
            .zhHant: "完整路線",
            .ja: "経路全体",
        ],
        "ios.routeGuide.stationCount": [
            .en: "{count} stations",
            .zhHans: "{count} 个车站",
            .zhHant: "{count} 個車站",
            .ja: "{count} 駅",
        ],
        "ios.routeGuide.choosePortion": [
            .en: "Choose the part to correct",
            .zhHans: "选择要纠正的区间",
            .zhHant: "選擇要糾正的區間",
            .ja: "修正する区間を選択",
        ],
        "ios.routeGuide.portionHelp": [
            .en: "Choose two recorded stations around the part of the route you want to change.",
            .zhHans: "选择出错部分前后的两个已记录车站。",
            .zhHant: "選擇出錯部分前後的兩個已記錄車站。",
            .ja: "変更する部分の前後にある記録済みの駅を選びます。",
        ],
        "ios.routeGuide.avoidHelp": [
            .en: "Choose a verified railway path that avoids the selected station. Your recorded ride stays unchanged until you apply it.",
            .zhHans: "选择绕开该车站的实际铁路走向，应用前行程保持原样。",
            .zhHant: "選擇繞開該車站的實際鐵路走向，套用前行程保持原樣。",
            .ja: "選択した駅を通らない鉄道経路を選びます。適用するまで記録は変わりません。",
        ],
        "ios.routeGuide.findPaths": [
            .en: "Compare railway paths",
            .zhHans: "比较铁路走向",
            .zhHant: "比較鐵路走向",
            .ja: "鉄道経路を比較",
        ],
        "ios.routeGuide.findingPaths": [
            .en: "Finding railway paths…",
            .zhHans: "正在查找铁路走向…",
            .zhHant: "正在尋找鐵路走向…",
            .ja: "鉄道経路を検索中…",
        ],
        "ios.routeGuide.occurrence": [
            .en: "Stop {number}: {station}",
            .zhHans: "第 {number} 站：{station}",
            .zhHant: "第 {number} 站：{station}",
            .ja: "{number} 番目の駅：{station}",
        ],
        "ios.routeGuide.invalidEndpoints": [
            .en: "Choose two mapped stations in travel order.",
            .zhHans: "请按行程顺序选择两个地图中的车站。",
            .zhHant: "請按行程順序選擇兩個地圖中的車站。",
            .ja: "乗車順に地図上の駅を二つ選んでください。",
        ],
        "ios.routeGuide.selectRange": [
            .en: "Choose the portion of your journey to check.",
            .zhHans: "选择需要检查的行程区间。",
            .zhHant: "選擇需要檢查的行程區間。",
            .ja: "確認する乗車区間を選びます。",
        ],
        "ios.routeGuide.removalTitle": [
            .en: "Remove recorded stations?",
            .zhHans: "删除已有车站记录？",
            .zhHant: "刪除已有車站記錄？",
            .ja: "記録済みの駅を削除しますか？",
        ],
        "ios.routeGuide.removalDetail": [
            .en: "This route does not pass {stations}. Removing these stations will remove their recorded times and platforms.",
            .zhHans: "此路线不经过 {stations}。删除这些车站将同时删除其时刻、站台及停站信息。",
            .zhHant: "此路線不經過 {stations}。刪除這些車站將同時刪除其時刻、月台及停站資訊。",
            .ja: "この経路は {stations} を通りません。削除すると各駅の時刻・番線・停車情報も削除されます。",
        ],
        "ios.routeGuide.removeAndApply": [
            .en: "Remove stations and apply route",
            .zhHans: "删除车站并应用路线",
            .zhHant: "刪除車站並套用路線",
            .ja: "駅を削除して経路を適用",
        ],
        "ios.routeGuide.undo": [
            .en: "Undo route change",
            .zhHans: "撤销路线修改",
            .zhHant: "復原路線修改",
            .ja: "経路の変更を取り消す",
        ],
        "ios.routeGuide.updated": [
            .en: "Added {added} stations, removed {removed}",
            .zhHans: "已补入 {added} 站，移除 {removed} 站",
            .zhHant: "已補入 {added} 站，移除 {removed} 站",
            .ja: "{added} 駅を追加、{removed} 駅を削除",
        ],
        "ios.routeGuide.undoUnavailable": [
            .en: "The corrected stations have been edited. Undo is no longer available.",
            .zhHans: "修改后的车站已再次编辑，无法直接撤销此次路线修改。",
            .zhHant: "修改後的車站已再次編輯，無法直接復原此次路線修改。",
            .ja: "修正した駅が再編集されているため、経路の変更を取り消せません。",
        ],
    ]
}
