import RailCore
import Testing

/// Parity between `LaneLOD.resolve` and `app/public/railmap-style.js`'s
/// `laneScaleForZoom`.
///
/// The table below was generated by running the JavaScript function directly
/// with Node and is embedded here literally rather than re-derived, so a
/// change to either side's arithmetic shows up as a mismatch instead of two
/// implementations quietly agreeing with themselves. Regenerate it with:
///
///   node -e "
///   global.window = global;
///   global.RailMapBasemap = { MAP_SURFACE_COLORS: {}, namespaceBasemap: (x)=>x };
///   global.RailNetwork = { DEFAULT_LINE_COLOR: '#000' };
///   require('./app/public/railmap-style.js');
///   const S = global.RailMapStyle;
///   const cases = [
///     [6, null], [8.9, null], [9, null], [10.5, null], [11.9, null], [12, null], [15, null],
///     [9.0, 0], [9.1, 0], [9.24, 0], [9.25, 0], [9.26, 0], [10, 0],
///     [9.0, 1], [8.76, 1], [8.75, 1], [8.74, 1], [8.0, 1],
///     [12.0, 1], [12.1, 1], [12.24, 1], [12.25, 1], [12.26, 1], [13, 1],
///     [12.0, 2], [11.76, 2], [11.75, 2], [11.74, 2], [11.0, 2],
///     [6, 2], [15, 0], [10, 99],
///   ];
///   for (const [zoom, prev] of cases) {
///     const r = S.laneScaleForZoom(zoom, prev);
///     const prevStr = prev === null ? 'nil' : String(prev);
///     console.log('        (zoom: ' + zoom + ', previous: ' + prevStr + ', bucket: ' + r.bucket + ', scale: ' + r.scale + '),');
///   }
///   "
///
/// run from the repository root, and pasted back into `cases` below.
struct LaneLODTests {
    struct Case {
        let zoom: Double
        let previous: Int?
        let bucket: Int
        let scale: Double
    }

    static let cases: [Case] = [
        // no previous bucket: the plain boundaries, across the whole range.
        Case(zoom: 6, previous: nil, bucket: 0, scale: 0),
        Case(zoom: 8.9, previous: nil, bucket: 0, scale: 0),
        Case(zoom: 9, previous: nil, bucket: 1, scale: 0.5),
        Case(zoom: 10.5, previous: nil, bucket: 1, scale: 0.5),
        Case(zoom: 11.9, previous: nil, bucket: 1, scale: 0.5),
        Case(zoom: 12, previous: nil, bucket: 2, scale: 1),
        Case(zoom: 15, previous: nil, bucket: 2, scale: 1),
        // boundary 9, moving UP from bucket 0: below / at / just past 9.25.
        Case(zoom: 9, previous: 0, bucket: 0, scale: 0),
        Case(zoom: 9.1, previous: 0, bucket: 0, scale: 0),
        Case(zoom: 9.24, previous: 0, bucket: 0, scale: 0),
        Case(zoom: 9.25, previous: 0, bucket: 1, scale: 0.5),
        Case(zoom: 9.26, previous: 0, bucket: 1, scale: 0.5),
        Case(zoom: 10, previous: 0, bucket: 1, scale: 0.5),
        // boundary 9, moving DOWN from bucket 1: at / just above / at / just below 8.75.
        Case(zoom: 9, previous: 1, bucket: 1, scale: 0.5),
        Case(zoom: 8.76, previous: 1, bucket: 1, scale: 0.5),
        Case(zoom: 8.75, previous: 1, bucket: 1, scale: 0.5),
        Case(zoom: 8.74, previous: 1, bucket: 0, scale: 0),
        Case(zoom: 8, previous: 1, bucket: 0, scale: 0),
        // boundary 12, moving UP from bucket 1: below / at / just past 12.25.
        Case(zoom: 12, previous: 1, bucket: 1, scale: 0.5),
        Case(zoom: 12.1, previous: 1, bucket: 1, scale: 0.5),
        Case(zoom: 12.24, previous: 1, bucket: 1, scale: 0.5),
        Case(zoom: 12.25, previous: 1, bucket: 2, scale: 1),
        Case(zoom: 12.26, previous: 1, bucket: 2, scale: 1),
        Case(zoom: 13, previous: 1, bucket: 2, scale: 1),
        // boundary 12, moving DOWN from bucket 2: at / just above / at / just below 11.75.
        Case(zoom: 12, previous: 2, bucket: 2, scale: 1),
        Case(zoom: 11.76, previous: 2, bucket: 2, scale: 1),
        Case(zoom: 11.75, previous: 2, bucket: 2, scale: 1),
        Case(zoom: 11.74, previous: 2, bucket: 1, scale: 0.5),
        Case(zoom: 11, previous: 2, bucket: 1, scale: 0.5),
        // multi-boundary jumps, and an out-of-range previous bucket.
        Case(zoom: 6, previous: 2, bucket: 0, scale: 0),
        Case(zoom: 15, previous: 0, bucket: 2, scale: 1),
        Case(zoom: 10, previous: 99, bucket: 1, scale: 0.5),
    ]

    @Test("matches railmap-style.js's laneScaleForZoom", arguments: cases)
    func matchesJavaScript(_ testCase: Case) {
        let resolved = LaneLOD.resolve(zoom: testCase.zoom, previousBucket: testCase.previous)
        #expect(resolved.bucket == testCase.bucket)
        #expect(resolved.scale == testCase.scale)
    }

    @Test("hysteresis holds the boundary against a jittering zoom")
    func hysteresisHoldsBoundary() {
        // Resting on bucket 1 side of z12, small jitter around 12 must not move it.
        var bucket: Int? = 1
        for zoom in [11.9, 12.0, 12.1, 11.95, 12.05, 11.9] {
            let resolved = LaneLOD.resolve(zoom: zoom, previousBucket: bucket)
            #expect(resolved.bucket == 1)
            bucket = resolved.bucket
        }
        // Clearing the hysteresis band commits the move, and jitter back
        // toward (but not past) the boundary does not un-commit it.
        let advanced = LaneLOD.resolve(zoom: 12.3, previousBucket: bucket)
        #expect(advanced.bucket == 2)
        let settled = LaneLOD.resolve(zoom: 12.0, previousBucket: advanced.bucket)
        #expect(settled.bucket == 2)
    }
}
